[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic==2.9.2",
    "pygame>=2.6.1",
    "pylsl>=1.17.6",
    "pyserial>=3.5",
    "requests==2.32.3",
    "rich==13.9.2",
]
